version: '3'

services:
  blue:
    build: ./app
    container_name: blue
    environment:
      - APP_COLOR=blue
    ports:
      - "5001:5000"

  green:
    build: ./app
    container_name: green
    environment:
      - APP_COLOR=green
    ports:
      - "5002:5000"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blue
      - green
